name: Deploy Next.js estático a GitHub Pages y Medición de Performance.

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instala dependencias
        run: npm ci
        working-directory: ./

      - name: Build estático
        run: npm run build && npm run export
        working-directory: ./

     
      - name: Instala Lighthouse CI
        run: npm install -g @lhci/cli http-server

      - name: Inicia servidor temporal
        working-directory: ./out
        run: |
          npx http-server -p 8080 &
          sleep 5

      - name: Ejecuta Lighthouse CI
        working-directory: ./
        run: |
          lhci autorun \
            --collect.url=http://localhost:8080 \
            --upload.target=temporary-public-storage


      - name: Sube artefacto
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: ./out


  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: static-site
          path: ./out

      - name: Configura Pages
        uses: actions/configure-pages@v5

      - name: Sube artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Publica en GitHub Pages
        uses: actions/deploy-pages@v4
